version: '3.1'
services:
  db:
    image: postgres:11
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
  dbtest:
    image: postgres:11
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbtest
    volumes:
      - ./data/postgres-data-test:/var/lib/postgresql/data
